name: Convert Markdown to PDF

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pandoc and pdflatex
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended

    - name: Convert to PDF
      run: |
        pandoc input.md -o output.pdf --pdf-engine=pdflatex
